package SpontaneousReplace.SpiderBiome.Mobs.WeavingWebSpider;

import SpontaneousReplace.SpiderBiome.Generic.SRSpider.SRSpiderAnimations;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;

/**
 * <b style="color:FFC800"><font size="+2">Animations：织网蜘蛛动画类</font></b>
 * <p><i><b style="color:FFC800"><font size="+1">织网蜘蛛的所有动画设置</font></b></i></p>
 * <style="color:FFC800">
 *
 * @author 刘 Saikel Orado 又称 “游戏极客-Saikel”
 * <p>Saikel Orado Liu aka ”GameGeek-Saikel“</p>
 * @version 2.0
 * | 创建于 2023/1/18 19:40
 */
@Environment(value = EnvType.CLIENT)
public abstract class Animations extends SRSpiderAnimations {
    /**
     * WALK: 行走动画 | 循环 | 0.18s
     */
    // region public static final Animation WALK = Animation.Builder.create(0.18f).looping().build();
    public static final Animation WALK = Animation.Builder.create(0.18f).looping()
            .addBoneAnimation("body",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.03f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.06f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.09f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.12f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.15f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.18f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("head",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.09f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.18f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("rightChelicera",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.06f, AnimationHelper.createTranslationalVector(-1f, 2f, -4f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.15f, AnimationHelper.createTranslationalVector(-1f, 1f, -2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.18f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("rightChelicera",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0.03f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.06f, AnimationHelper.createRotationalVector(-15f, 22.5f, -15f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.09f, AnimationHelper.createRotationalVector(-17.5f, 10f, -15f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.12f, AnimationHelper.createRotationalVector(-15f, 22.5f, -15f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.15f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.18f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leftChelicera",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.06f, AnimationHelper.createTranslationalVector(1f, 2f, -4f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.15f, AnimationHelper.createTranslationalVector(1f, 1f, -2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.18f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leftChelicera",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0.03f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.06f, AnimationHelper.createRotationalVector(-15f, -15f, 20f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.09f, AnimationHelper.createRotationalVector(-17.5f, -10f, 15f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.12f, AnimationHelper.createRotationalVector(-15f, -15f, 20f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.15f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.18f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("abdomen",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.09f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.18f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("rightHindLeg",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.06f, AnimationHelper.createTranslationalVector(1f, 3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.09f, AnimationHelper.createTranslationalVector(1f, 1.25f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.12f, AnimationHelper.createTranslationalVector(1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.18f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("rightHindLeg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.03f, AnimationHelper.createRotationalVector(10f, -5f, 15f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.06f, AnimationHelper.createRotationalVector(-2.1727649472472876f, -18.962245791191435f, -3.4645507291015747f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.12f, AnimationHelper.createRotationalVector(2.5f, 0f, 7.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.18f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leftHindLeg",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.03f, AnimationHelper.createTranslationalVector(-1f, -1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.06f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.09f, AnimationHelper.createTranslationalVector(-0.5f, 1f, -0.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.12f, AnimationHelper.createTranslationalVector(-1f, 2f, -1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.18f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leftHindLeg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.03f, AnimationHelper.createRotationalVector(0f, 0f, -10f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.06f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.09f, AnimationHelper.createRotationalVector(10f, 5f, -15f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.12f, AnimationHelper.createRotationalVector(0f, 15f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.18f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("rightMiddleLeg",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.03f, AnimationHelper.createTranslationalVector(-1f, 1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.06f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.09f, AnimationHelper.createTranslationalVector(0f, 0.75f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.12f, AnimationHelper.createTranslationalVector(0f, 1.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.18f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("rightMiddleLeg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.03f, AnimationHelper.createRotationalVector(0f, 0f, -5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.06f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.09f, AnimationHelper.createRotationalVector(0f, -7.5f, 10f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.12f, AnimationHelper.createRotationalVector(0f, -15f, -5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.18f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leftMiddleLeg",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.06f, AnimationHelper.createTranslationalVector(0f, 1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.09f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.12f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.18f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leftMiddleLeg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.03f, AnimationHelper.createRotationalVector(0f, 7.5f, -10f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.06f, AnimationHelper.createRotationalVector(0f, 15f, 2.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.12f, AnimationHelper.createRotationalVector(2.5f, -1f, -2.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.18f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("rightMiddleFrontLeg",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.06f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.09f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.12f, AnimationHelper.createTranslationalVector(0f, 1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.18f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("rightMiddleFrontLeg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.03f, AnimationHelper.createRotationalVector(0f, -5f, 10f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.06f, AnimationHelper.createRotationalVector(1.1652385950142161f, -12.474573527445955f, -2.758064389334322f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.12f, AnimationHelper.createRotationalVector(2.5f, 5.0f, -5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.18f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leftMiddleFrontLeg",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.03f, AnimationHelper.createTranslationalVector(-1f, -1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.06f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.09f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.12f, AnimationHelper.createTranslationalVector(0f, -2f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.18f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leftMiddleFrontLeg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.03f, AnimationHelper.createRotationalVector(0f, 0f, -5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.06f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.09f, AnimationHelper.createRotationalVector(-5f, 10f, -12.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.12f, AnimationHelper.createRotationalVector(0f, 17.5f, -5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.18f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("rightFrontLeg",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.03f, AnimationHelper.createTranslationalVector(-1f, 1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.06f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.09f, AnimationHelper.createTranslationalVector(-0.5f, -1.5f, -0.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.12f, AnimationHelper.createTranslationalVector(-1f, -3f, -1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.18f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("rightFrontLeg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.03f, AnimationHelper.createRotationalVector(0f, 0f, -7.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.06f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.09f, AnimationHelper.createRotationalVector(-17.5f, -10f, 22.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.12f, AnimationHelper.createRotationalVector(-7.790109976980148f, -19.659352527003648f, 9.24832393711813f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.18f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leftFrontLeg",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.06f, AnimationHelper.createTranslationalVector(1f, 0f, -2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.09f, AnimationHelper.createTranslationalVector(1f, 1f, -1.8900000000000001f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.12f, AnimationHelper.createTranslationalVector(1f, 2f, -1.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.18f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leftFrontLeg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.03f, AnimationHelper.createRotationalVector(-10f, 5f, -15f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.06f, AnimationHelper.createRotationalVector(5f, 7.5f, 5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.12f, AnimationHelper.createRotationalVector(7.5f, -10f, 10f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.18f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .build();
    // endregion
    /**
     * WEAVE: 筑网动画 | 单次 | 1.5s
     */
    // region public static final Animation WEAVE = Animation.Builder.create(1.5f).build();
    public static final Animation WEAVE = Animation.Builder.create(1.5f)
            .addBoneAnimation("body",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createRotationalVector(20f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4f, AnimationHelper.createRotationalVector(20f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("head",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createRotationalVector(-20f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createRotationalVector(-12.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createRotationalVector(-20f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8f, AnimationHelper.createRotationalVector(-12.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(-20f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2f, AnimationHelper.createRotationalVector(-12.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4f, AnimationHelper.createRotationalVector(-20f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("rightChelicera",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createRotationalVector(0f, 0f, -12.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4f, AnimationHelper.createRotationalVector(0f, 0f, -12.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(0f, 0f, -12.5f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leftChelicera",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createRotationalVector(0f, 0f, 12.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4f, AnimationHelper.createRotationalVector(0f, 0f, 12.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(0f, 0f, 12.5f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("rightMiddleFrontLeg",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createTranslationalVector(0f, 0f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4f, AnimationHelper.createTranslationalVector(0f, 0f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("rightMiddleFrontLeg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createRotationalVector(0f, -4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 10f, 12.50f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3f, AnimationHelper.createRotationalVector(0f, 25f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4f, AnimationHelper.createRotationalVector(0f, 25f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.45f, AnimationHelper.createRotationalVector(0f, 10f, 12.50f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leftMiddleFrontLeg",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createTranslationalVector(0f, 0f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4f, AnimationHelper.createTranslationalVector(0f, 0f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leftMiddleFrontLeg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createRotationalVector(0f, 4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, -10f, -12.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3f, AnimationHelper.createRotationalVector(0f, -25f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4f, AnimationHelper.createRotationalVector(0f, -25f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.45f, AnimationHelper.createRotationalVector(0f, -10f, -12.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("rightFrontLeg",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createTranslationalVector(0f, -1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4f, AnimationHelper.createTranslationalVector(0f, -1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("rightFrontLeg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createRotationalVector(0f, -5f, 5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4f, AnimationHelper.createRotationalVector(0f, -5f, 5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leftFrontLeg",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createTranslationalVector(0f, -1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4f, AnimationHelper.createTranslationalVector(0f, -1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leftFrontLeg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createRotationalVector(0f, 5f, -5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4f, AnimationHelper.createRotationalVector(0f, 5f, -5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("abdomen",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createTranslationalVector(0f, 0.75f, -3.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3f, AnimationHelper.createTranslationalVector(0f, 0.25f, -2.25f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createTranslationalVector(0f, 0.75f, -3.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0.25f, -2.25f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createTranslationalVector(0f, 0.75f, -3.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createTranslationalVector(0f, 0.25f, -2.25f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8f, AnimationHelper.createTranslationalVector(0f, 0.75f, -3.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9f, AnimationHelper.createTranslationalVector(0f, 0.25f, -2.25f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0.75f, -3.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.1f, AnimationHelper.createTranslationalVector(0f, 0.25f, -2.25f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2f, AnimationHelper.createTranslationalVector(0f, 0.75f, -3.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.3f, AnimationHelper.createTranslationalVector(0f, 0.25f, -2.25f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4f, AnimationHelper.createTranslationalVector(0f, 0.75f, -3.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("abdomen",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createRotationalVector(-45f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3f, AnimationHelper.createRotationalVector(-32.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createRotationalVector(-45f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(-32.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createRotationalVector(-45f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createRotationalVector(-32.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8f, AnimationHelper.createRotationalVector(-45f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9f, AnimationHelper.createRotationalVector(-32.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(-45f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.1f, AnimationHelper.createRotationalVector(-32.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2f, AnimationHelper.createRotationalVector(-45f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.3f, AnimationHelper.createRotationalVector(-32.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4f, AnimationHelper.createRotationalVector(-45f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("abdomen",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(0.2f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3f, AnimationHelper.createScalingVector(1.2f, 1.2f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createScalingVector(1.2f, 1.2f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createScalingVector(1.2f, 1.2f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9f, AnimationHelper.createScalingVector(1.2f, 1.2f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.1f, AnimationHelper.createScalingVector(1.2f, 1.2f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.3f, AnimationHelper.createScalingVector(1.2f, 1.2f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("rightHindLeg",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0.2f, AnimationHelper.createTranslationalVector(-1f, 0f, 2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3f, AnimationHelper.createTranslationalVector(0f, 0f, 2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createTranslationalVector(-1f, 0f, 2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0f, 2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createTranslationalVector(-1f, 0f, 2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createTranslationalVector(0f, 0f, 2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8f, AnimationHelper.createTranslationalVector(-1f, 0f, 2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9f, AnimationHelper.createTranslationalVector(0f, 0f, 2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(-1f, 0f, 2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.1f, AnimationHelper.createTranslationalVector(0f, 0f, 2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2f, AnimationHelper.createTranslationalVector(-1f, 0f, 2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.3f, AnimationHelper.createTranslationalVector(0f, 0f, 2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4f, AnimationHelper.createTranslationalVector(-1f, 0f, 2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("rightHindLeg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createRotationalVector(-60f, 5f, -50f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3f, AnimationHelper.createRotationalVector(-22.5f, 22.5f, -10f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createRotationalVector(-60f, 5f, -50f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(-22.5f, 22.5f, -10f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createRotationalVector(-60f, 5f, -50f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createRotationalVector(-22.5f, 22.5f, -10f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8f, AnimationHelper.createRotationalVector(-60f, 5f, -50f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9f, AnimationHelper.createRotationalVector(-22.5f, 22.5f, -10f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(-60f, 5f, -50f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.1f, AnimationHelper.createRotationalVector(-22.5f, 22.5f, -10f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2f, AnimationHelper.createRotationalVector(-60f, 5f, -50f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.3f, AnimationHelper.createRotationalVector(-22.5f, 22.5f, -10f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4f, AnimationHelper.createRotationalVector(-60f, 5f, -50f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leftHindLeg",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0.2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3f, AnimationHelper.createTranslationalVector(1f, 0f, 2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createTranslationalVector(0f, 0f, 2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(1f, 0f, 2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createTranslationalVector(0f, 0f, 2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createTranslationalVector(1f, 0f, 2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8f, AnimationHelper.createTranslationalVector(0f, 0f, 2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9f, AnimationHelper.createTranslationalVector(1f, 0f, 2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.1f, AnimationHelper.createTranslationalVector(1f, 0f, 2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2f, AnimationHelper.createTranslationalVector(0f, 0f, 2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.3f, AnimationHelper.createTranslationalVector(1f, 0f, 2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4f, AnimationHelper.createTranslationalVector(0f, 0f, 2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leftHindLeg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createRotationalVector(-5f, -5f, -12.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3f, AnimationHelper.createRotationalVector(-60f, -5f, 50f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createRotationalVector(-22.5f, -22.5f, 10f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(-60f, -5f, 50f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createRotationalVector(-22.5f, -22.5f, 10f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createRotationalVector(-60f, -5f, 50f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8f, AnimationHelper.createRotationalVector(-22.5f, -22.5f, 10f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9f, AnimationHelper.createRotationalVector(-60f, -5f, 50f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(-22.5f, -22.5f, 10f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.1f, AnimationHelper.createRotationalVector(-60f, -5f, 50f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2f, AnimationHelper.createRotationalVector(-22.5f, -22.5f, 10f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.3f, AnimationHelper.createRotationalVector(-60f, -5f, 50f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4f, AnimationHelper.createRotationalVector(-22.5f, -22.5f, 10f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("rightMiddleLeg",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3f, AnimationHelper.createTranslationalVector(-3f, 0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(-3f, 0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createTranslationalVector(-3f, 0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9f, AnimationHelper.createTranslationalVector(-3f, 0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.1f, AnimationHelper.createTranslationalVector(-3f, 0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.3f, AnimationHelper.createTranslationalVector(-3f, 0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("rightMiddleLeg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createRotationalVector(0f, 30f, 5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3f, AnimationHelper.createRotationalVector(-30f, 30f, -50f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createRotationalVector(0f, 30f, 5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(-30f, 30f, -50f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createRotationalVector(0f, 30f, 5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createRotationalVector(-30f, 30f, -50f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8f, AnimationHelper.createRotationalVector(0f, 30f, 5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9f, AnimationHelper.createRotationalVector(-30f, 30f, -50f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 30f, 5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.1f, AnimationHelper.createRotationalVector(-30f, 30f, -50f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2f, AnimationHelper.createRotationalVector(0f, 30f, 5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.3f, AnimationHelper.createRotationalVector(-30f, 30f, -50f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4f, AnimationHelper.createRotationalVector(0f, 30f, 5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leftMiddleLeg",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createTranslationalVector(3f, 0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createTranslationalVector(3f, 0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8f, AnimationHelper.createTranslationalVector(3f, 0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(3f, 0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.1f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2f, AnimationHelper.createTranslationalVector(3f, 0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.3f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4f, AnimationHelper.createTranslationalVector(3f, 0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leftMiddleLeg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createRotationalVector(0f, -10f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3f, AnimationHelper.createRotationalVector(0f, -30f, -5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createRotationalVector(-30f, -30f, 50f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, -30f, -5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createRotationalVector(-30f, -30f, 50f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createRotationalVector(0f, -30f, -5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8f, AnimationHelper.createRotationalVector(-30f, -30f, 50f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9f, AnimationHelper.createRotationalVector(0f, -30f, -5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(-30f, -30f, 50f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.1f, AnimationHelper.createRotationalVector(0f, -30f, -5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2f, AnimationHelper.createRotationalVector(-30f, -30f, 50f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.3f, AnimationHelper.createRotationalVector(0f, -30f, -5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4f, AnimationHelper.createRotationalVector(-30f, -30f, 50f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("rightJaw",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createTranslationalVector(-0.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3f, AnimationHelper.createTranslationalVector(0.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createTranslationalVector(-0.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createTranslationalVector(-0.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createTranslationalVector(0.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8f, AnimationHelper.createTranslationalVector(-0.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9f, AnimationHelper.createTranslationalVector(0.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(-0.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.1f, AnimationHelper.createTranslationalVector(0.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2f, AnimationHelper.createTranslationalVector(-0.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.3f, AnimationHelper.createTranslationalVector(0.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4f, AnimationHelper.createTranslationalVector(-0.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leftJaw",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2f, AnimationHelper.createTranslationalVector(0.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3f, AnimationHelper.createTranslationalVector(-0.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4f, AnimationHelper.createTranslationalVector(0.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(-0.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6f, AnimationHelper.createTranslationalVector(0.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7f, AnimationHelper.createTranslationalVector(-0.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8f, AnimationHelper.createTranslationalVector(0.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9f, AnimationHelper.createTranslationalVector(-0.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.1f, AnimationHelper.createTranslationalVector(-0.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2f, AnimationHelper.createTranslationalVector(0.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.3f, AnimationHelper.createTranslationalVector(-0.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4f, AnimationHelper.createTranslationalVector(0.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .build();

    // endregion
}
