/*
 * MIT License
 *
 * Copyright (c) 2023 GameGeek-Saikel
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package pers.saikel0rado1iu.sr.variant.spider.mob.larva;

import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;
import pers.saikel0rado1iu.sr.variant.spider.mob.general.SpiderAnimations;

/**
 * <h2 style="color:FFC800">幼蛛动画类</h2>
 *
 * @author <a href="https://github.com/Saikel-Orado-Liu"><img alt="author" src="https://avatars.githubusercontent.com/u/88531138?s=64&v=4"></a>
 */
public interface SpiderLarvaAnimations extends SpiderAnimations {
	/**
	 * WALK: 行走动画 | 循环 | 0.18s
	 */
	// region Animation WALK = Animation.Builder.create(0.18f).looping().build();
	Animation WALK = Animation.Builder.create(0.18f).looping()
			.addBoneAnimation("body",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.03f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.06f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.09f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.12f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.15f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.18f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("head",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.09f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.18f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("rightChelicera",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.06f, AnimationHelper.createTranslationalVector(-1f, 2f, -4f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.15f, AnimationHelper.createTranslationalVector(-1f, 1f, -2f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.18f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("rightChelicera",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0.03f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.06f, AnimationHelper.createRotationalVector(-15f, 22.5f, -15f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.09f, AnimationHelper.createRotationalVector(-17.5f, 10f, -15f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.12f, AnimationHelper.createRotationalVector(-15f, 22.5f, -15f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.15f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.18f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftChelicera",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.06f, AnimationHelper.createTranslationalVector(1f, 2f, -4f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.15f, AnimationHelper.createTranslationalVector(1f, 1f, -2f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.18f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftChelicera",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0.03f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.06f, AnimationHelper.createRotationalVector(-15f, -15f, 20f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.09f, AnimationHelper.createRotationalVector(-17.5f, -10f, 15f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.12f, AnimationHelper.createRotationalVector(-15f, -15f, 20f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.15f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.18f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("abdomen",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.09f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.18f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("rightHindLeg",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.06f, AnimationHelper.createTranslationalVector(1f, 3f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.09f, AnimationHelper.createTranslationalVector(1f, 1.25f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.12f, AnimationHelper.createTranslationalVector(1f, -0.5f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.18f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("rightHindLeg",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.03f, AnimationHelper.createRotationalVector(10f, -5f, 15f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.06f, AnimationHelper.createRotationalVector(-2.1727649472472876f, -18.962245791191435f, -3.4645507291015747f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.12f, AnimationHelper.createRotationalVector(2.5f, 0f, 7.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.18f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftHindLeg",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.03f, AnimationHelper.createTranslationalVector(-1f, -1f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.06f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.09f, AnimationHelper.createTranslationalVector(-0.5f, 1f, -0.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.12f, AnimationHelper.createTranslationalVector(-1f, 2f, -1f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.18f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftHindLeg",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.03f, AnimationHelper.createRotationalVector(0f, 0f, -10f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.06f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.09f, AnimationHelper.createRotationalVector(10f, 5f, -15f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.12f, AnimationHelper.createRotationalVector(0f, 15f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.18f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("rightMiddleLeg",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.03f, AnimationHelper.createTranslationalVector(-1f, 1f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.06f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.09f, AnimationHelper.createTranslationalVector(0f, 0.75f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.12f, AnimationHelper.createTranslationalVector(0f, 1.5f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.18f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("rightMiddleLeg",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.03f, AnimationHelper.createRotationalVector(0f, 0f, -5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.06f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.09f, AnimationHelper.createRotationalVector(0f, -7.5f, 10f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.12f, AnimationHelper.createRotationalVector(0f, -15f, -5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.18f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftMiddleLeg",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.06f, AnimationHelper.createTranslationalVector(0f, 1f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.09f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.12f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.18f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftMiddleLeg",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.03f, AnimationHelper.createRotationalVector(0f, 7.5f, -10f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.06f, AnimationHelper.createRotationalVector(0f, 15f, 2.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.12f, AnimationHelper.createRotationalVector(2.5f, -1f, -2.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.18f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("rightMiddleFrontLeg",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.06f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.09f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.12f, AnimationHelper.createTranslationalVector(0f, 1f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.18f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("rightMiddleFrontLeg",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.03f, AnimationHelper.createRotationalVector(0f, -5f, 10f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.06f, AnimationHelper.createRotationalVector(1.1652385950142161f, -12.474573527445955f, -2.758064389334322f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.12f, AnimationHelper.createRotationalVector(2.5f, 5.0f, -5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.18f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftMiddleFrontLeg",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.03f, AnimationHelper.createTranslationalVector(-1f, -1f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.06f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.09f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.12f, AnimationHelper.createTranslationalVector(0f, -2f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.18f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftMiddleFrontLeg",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.03f, AnimationHelper.createRotationalVector(0f, 0f, -5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.06f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.09f, AnimationHelper.createRotationalVector(-5f, 10f, -12.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.12f, AnimationHelper.createRotationalVector(0f, 17.5f, -5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.18f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("rightFrontLeg",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.03f, AnimationHelper.createTranslationalVector(-1f, 1f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.06f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.09f, AnimationHelper.createTranslationalVector(-0.5f, -1.5f, -0.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.12f, AnimationHelper.createTranslationalVector(-1f, -3f, -1f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.18f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("rightFrontLeg",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.03f, AnimationHelper.createRotationalVector(0f, 0f, -7.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.06f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.09f, AnimationHelper.createRotationalVector(-17.5f, -10f, 22.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.12f, AnimationHelper.createRotationalVector(-7.790109976980148f, -19.659352527003648f, 9.24832393711813f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.18f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftFrontLeg",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.06f, AnimationHelper.createTranslationalVector(1f, 0f, -2f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.09f, AnimationHelper.createTranslationalVector(1f, 1f, -1.8900000000000001f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.12f, AnimationHelper.createTranslationalVector(1f, 2f, -1.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.18f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftFrontLeg",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.03f, AnimationHelper.createRotationalVector(-10f, 5f, -15f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.06f, AnimationHelper.createRotationalVector(5f, 7.5f, 5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.12f, AnimationHelper.createRotationalVector(7.5f, -10f, 10f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.18f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.build();
	// endregion
	/**
	 * SWIM: 游泳动画 | 循环 | 0.6s
	 */
	// region Animation SWIM = Animation.Builder.create(0.6f).looping().build();
	Animation SWIM = Animation.Builder.create(0.6f).looping()
			.addBoneAnimation("body",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.1f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.3f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.4f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.6f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("head",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.1f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.3f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.4f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.5f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.6f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("rightChelicera",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.2f, AnimationHelper.createTranslationalVector(-1f, 2f, -4f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.5f, AnimationHelper.createTranslationalVector(-1f, 1f, -2f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.6f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("rightChelicera",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0.1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.2f, AnimationHelper.createRotationalVector(-15f, 22.5f, -15f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.3f, AnimationHelper.createRotationalVector(-17.5f, 10f, -15f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.4f, AnimationHelper.createRotationalVector(-15f, 22.5f, -15f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.6f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftChelicera",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.2f, AnimationHelper.createTranslationalVector(1f, 2f, -4f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.5f, AnimationHelper.createTranslationalVector(1f, 1f, -2f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.6f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftChelicera",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0.1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.2f, AnimationHelper.createRotationalVector(-15f, -15f, 20f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.3f, AnimationHelper.createRotationalVector(-17.5f, -10f, 15f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.4f, AnimationHelper.createRotationalVector(-15f, -15f, 20f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.6f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("abdomen",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.1f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.3f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.4f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.5f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.6f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("rightHindLeg",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.2f, AnimationHelper.createTranslationalVector(1f, 3f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.3f, AnimationHelper.createTranslationalVector(1f, 1.25f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.4f, AnimationHelper.createTranslationalVector(1f, -0.5f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.6f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("rightHindLeg",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.1f, AnimationHelper.createRotationalVector(10f, -5f, 15f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.2f, AnimationHelper.createRotationalVector(-2.17f, -18.96f, -3.46f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.4f, AnimationHelper.createRotationalVector(2.5f, 0f, 7.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.6f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftHindLeg",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.1f, AnimationHelper.createTranslationalVector(-1f, -1f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.3f, AnimationHelper.createTranslationalVector(-0.5f, 1f, -0.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.4f, AnimationHelper.createTranslationalVector(-1f, 2f, -1f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.6f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftHindLeg",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.1f, AnimationHelper.createRotationalVector(0f, 0f, -10f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.3f, AnimationHelper.createRotationalVector(10f, 5f, -15f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.4f, AnimationHelper.createRotationalVector(0f, 15f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.6f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("rightMiddleLeg",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.1f, AnimationHelper.createTranslationalVector(-1f, 1f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.3f, AnimationHelper.createTranslationalVector(0f, 0.75f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.4f, AnimationHelper.createTranslationalVector(0f, 1.5f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.6f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("rightMiddleLeg",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.1f, AnimationHelper.createRotationalVector(0f, 0f, -5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.3f, AnimationHelper.createRotationalVector(0f, -7.5f, 10f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.4f, AnimationHelper.createRotationalVector(0f, -15f, -5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.6f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftMiddleLeg",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.2f, AnimationHelper.createTranslationalVector(0f, 1f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.3f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.4f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.6f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftMiddleLeg",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.1f, AnimationHelper.createRotationalVector(0f, 7.5f, -10f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.2f, AnimationHelper.createRotationalVector(0f, 15f, 2.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.4f, AnimationHelper.createRotationalVector(2.5f, -1f, -2.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.6f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("rightMiddleFrontLeg",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.3f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.4f, AnimationHelper.createTranslationalVector(0f, 1f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.6f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("rightMiddleFrontLeg",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.1f, AnimationHelper.createRotationalVector(0f, -5f, 10f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.2f, AnimationHelper.createRotationalVector(1.17f, -12.47f, -2.76f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.4f, AnimationHelper.createRotationalVector(2.5f, 5f, -5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.6f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftMiddleFrontLeg",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.1f, AnimationHelper.createTranslationalVector(-1f, -1f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.3f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.4f, AnimationHelper.createTranslationalVector(0f, -2f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.6f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftMiddleFrontLeg",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.1f, AnimationHelper.createRotationalVector(0f, 0f, -5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.3f, AnimationHelper.createRotationalVector(-5f, 10f, -12.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.4f, AnimationHelper.createRotationalVector(0f, 17.5f, -5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.6f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("rightFrontLeg",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.1f, AnimationHelper.createTranslationalVector(-1f, 1f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.3f, AnimationHelper.createTranslationalVector(-0.5f, -1.5f, -0.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.4f, AnimationHelper.createTranslationalVector(-1f, -3f, -1f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.6f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("rightFrontLeg",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.1f, AnimationHelper.createRotationalVector(0f, 0f, -7.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.3f, AnimationHelper.createRotationalVector(-17.5f, -10f, 22.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.4f, AnimationHelper.createRotationalVector(-7.79f, -19.66f, 9.25f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.6f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftFrontLeg",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.2f, AnimationHelper.createTranslationalVector(1f, 0f, -2f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.3f, AnimationHelper.createTranslationalVector(1f, 1f, -1.89f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.4f, AnimationHelper.createTranslationalVector(1f, 2f, -1.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.6f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftFrontLeg",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.1f, AnimationHelper.createRotationalVector(-10f, 5f, -15f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.2f, AnimationHelper.createRotationalVector(5f, 7.5f, 5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.4f, AnimationHelper.createRotationalVector(7.5f, -10f, 10f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.6f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR))).build();
	//endregion
}
